name: myanime
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.9
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^10.0.0
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.5
  lottie: ^2.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - images/linkedin.png
    - images/github.png
    - images/email.png
    - images/wira.jpeg
    - images/ # Folder gambar untuk akses lainnya

  uses-material-design: true
